title: My Projects
name: Marco
description: Things I've built

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
